version: '2'

services:

  app:
    image: odoo:9
    container_name: myevo_app
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - myevo_odoo-web-data:/var/lib/odoo
      - ./app/myevo_odoo_addons:/mnt/extra-addons
    environment:
      - PYTHONUNBUFFERED=1
      - USER=admin
      - PASSWORD=admin

  db:
    image: postgres:9.5.10
    container_name: myevo_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - myevo_odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  myevo_odoo-web-data:
  myevo_odoo-db-data: